### ISSUE TITLE
Probleme dans la documentation

### ISSUE THREAD

**Issue by landaisbenj** [hacf-fr/lovelace-meteofrance-weather-card#76]
Hello.

Je pense qu'il y a un problème dans la documentation.

J'ai essayé de la suivre, mais je n'ai pas reussi. Au niveau de l'installation via HACS le menu "3 points" avec le custom repository ne se trouve que dans la page "frontend".
Ensuite lorsque j'ai réussi à installer le repo, je n'ai pas trouver de bouton reload.... (J'ai cependant redémarré).
Mais même après tout ça, je n'ai pas trouvé la carte quand j'ai voulu la configurer, il a fallu que je rajoute la partie suivante de "l'installation manuelle" : Maintenant depuis votre interface HA, allez dans Configuration > Lovelace Dashboard > Resources et créer une ressource de type JavaScript Module et pour url /local/community/lovelace-meteofrance-weather-card/meteofrance-weather-card.js.
Soit il manque l'info dans la partie installation via HACS, soit il manque une phase que je ne connais pas..

**Comment by dx44** [comment]
Salut @landaisbenj,
HACS évolue et la documentation ne suit pas forcément :)
Pour l'accès au menu, il nous faut corriger effectivement.
En ce qui concernce le module, il devrait s'incrire tout seul, tu n'es pas le seul à le remonter, c'est un peu aléatoire, pour certains il s'incrit correctement ... à creuser !
Tu peux contribuer et proposer une modification directement ici sur GitHub en éditant la documentation et en faisant un 'Pull Request'.

**Comment by landaisbenj** [comment]
Ok merci pour l’info. J’essaierai d’éditer pour modifier en attendant que le problème soit résolu. Pour le problème d’inscription automatique, J’ajouterai peut-être une issue dans ce sens aussi pour le suivi.

**Comment by mielune** [comment]
Bonjour la communaute,

J'ai le souci de la carte qui ne s'ajoute pas.
Rien vu dans les logs.
J'ai essaye de suivre la partie installation manuelle, mais dans Configuration > Lovelace, j'ai pas le sous menu Ressources ... que faire ?
J'ai aussi essaye avec l'ajout dans le fichier /config/ui-lovelace.yaml mais rien de plus.

Utilisation d'un HA Core tout neuf dans une stack Docker Swarm en version 2020.12.1.
La carte est bien installe dans le dossier /config/www/community/lovelace-meteofrance-weather-card/

Si vous avez une piste ?

Et merci pour ce beau travail :) Je suis nouveau dans HA et qu'elle communaute !

**Comment by landaisbenj** [comment]
Regarde en tant qu’onglet plutôt que menu.

**Comment by mielune** [comment]
Bien vu :) Mais pas mieu, rien de plus en haut dans les ongets, saisie d'ecran en PJ si ca peut aider ;)

![Screenshot from 2020-12-28 11-58-11](https://user-images.githubusercontent.com/8350742/103209801-3b636a80-4904-11eb-9425-96c77bf9e00b.png)

**Comment by mielune** [comment]
configuration de base, peut etre trop simle ?
Voici le contenu du `configuration.yaml`

```yaml
default_config:

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

knx:
  config_file: '/config/xknx.yaml'

logger:
  default: warning
  logs:
    xknx: debug
```
